### ISSUE TITLE
Cannot build openni from AUR

### ISSUE THREAD

**Issue by jwhendy** [ros-melodic-arch/ros-melodic-openni-launch#1]
I'm unable to build [openni](https://aur.archlinux.org/packages/openni/), so I'm not able to update/verify the `ros-melodic-openni*` packages.

**Comment by acxz** [comment]
I was actually able to build `openni` from the AUR. Can you post your build log?

**Comment by jwhendy** [comment]
This turned out to be a java issue. It wasn't finding `javac` due to past `jre8/jdk8` installs and not updating `archlinux-java` to update the paths to `jdk12`.
